service: gpt-helper

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "cloudwatch:Get*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
        - "lambda:GetFunction"
      Resource: "*"
  environment:
    ENV: ${self:custom.stage}

# you can add packaging information here
package:
  include:
    - server/**
    - modules/**
    - dependencies/**
  exclude:
    - serverless.yml
    - requirements.txt
    - requirements_local.txt
    - tests/**
    - "**/__pycache__/**"
    - "**/env/**"
    - "**/.vscode/**"

functions:
  answers:
    handler: app.lambda_handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
custom:
  stage: "${opt:stage, self:provider.stage}"
  pythonRequirements:
    dockerizePip: true
    fileName: requirements.txt
    useStaticCache: false

plugins:
  - serverless-python-requirements
